### ISSUE TITLE
Modularise code

### ISSUE THREAD

**Issue by pbywater** [FAC10/Genie-in-a-Bot#25]
- [x] Storing our responses nicely
- [x] Dealing with different kinds of media we receive/send

**Comment by ghost** [comment]
by the way, [this](http://javascriptplayground.com/blog/2014/07/testing-express-routes/) site talks a little bit about modularising express routes. Might be worth looking at

**Comment by ghost** [comment]
Turns out we need to use express.Router() in the routes when we modularise, and then import the routes into our main app and use app.use('/', routes) to actually implement them.
