### ISSUE TITLE
Extract user's name

### ISSUE THREAD

**Issue by pbywater** [FAC10/Genie-in-a-Bot#31]
https://developers.facebook.com/docs/messenger-platform/user-profile

**Comment by ghost** [comment]
What we need to do is query this API:

https://graph.facebook.com/v2.6/<USER_ID>?access_token=PAGE_ACCESS_TOKEN

Where User_ID is the id of the user we want to get the name of, and page_access_token is the same as the one in our config.env

The ID for the sender of each message is found in the 'event' object that we pass into receivedMessage() (event.sender.id)
